config/routes.rb
Geopost::Application.routes.draw do

  
  
root "posts#index"
  resources :posts do
    resources :comments
  end

 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments

validates :title, presence: true, uniqueness: true
validates :body, length: {minimum: 1 }

#validates takes arguments- Name of the column, thing you are validation: what it needs to pass
# presence: true - is just a hash!
#length is a key to a hash and the value is another hash with the hey of minimum

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	  before_action :find_post, only: [:new, :create, :edit, :update]


	 	def new	  	
	  		@comment = @post.comments.new
	 	end


	  	def create
	  	
		    @comment = @post.comments.new(comment_params)
			    if @comment.save
			        flash[:success] = "Success! (comment)"
			      redirect_to post_path(@post)
			    else
			      flash[:error] = "Oops, something went wrong, please try again (comment)"
			      render :new
			  	end
	  	end


		def edit
			@comment = @post.comments.find(params[:id])
		end

		
		def update
	    #@post = Post.find(params[:id])
	   		@comment = @post.comments.find(params[:id])

	        if @comment.update(comment_params)
	      		flash[:success] = "Successfully updated comment"
	        	redirect_to post_path(@post)
			else
	        	flash[:error] = "Oops, something went wrong with that comment, please try again"
	        	render :edit
	      	end
	    end
  
	private
		def comment_params
			params.require(:comment).permit(:body)
		end


		def find_post
		 @post = Post.find(params[:post_id])
		end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :find_post, except: [:index, :new, :create]

# runs the find_post method before all of these so that you always have the post you are refering to
# before_action - a class method that is built in
# need to say which of the methods you want it to be run before
# :except - is the key to a hash

  def index
    if params[:featured].present? and params[:featured] == "true"
      #get only the featured posts 
      @posts = Post.where(is_featured: true).order("created_at DESC")
    else
  	  @posts = Post.order("created_at DESC")
    end
  end
  # true is in quotes as it is being returned as a string, not a boolean value
  # 


    def show
      @comments = @post.comments
  #	@post = Post.find(params[:id])
  end
 # each of these @posts are only available within their methods (which is why you are using the @ symbol!!)

  def new
    @post = Post.new

  end

# The new form gets submitted to the create action
  
  def create
    @post = Post.new(post_params)
      if @post.save
        flash[:success] = "Success!"
      redirect_to root_path
    else
      flash[:error] = "Oops, something went wrong, please try again"
      render :new
    end
  end


#flash is a hash, [:error] is reading the key

 ###################RELATED########

  def edit
    #@post = Post.find(params[:id])
  end

# The edit action gets submitted to the update action
  
  def update
    #@post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:success] = "Success! Updated '#{@post.title}'"
        redirect_to post_path(@post)
      else
        flash[:error] = "Oops, something went wrong, please try again"
        render :edit
      end
  end

  #render means that nothing saved. Had we redirected instead, it would have saved it

####################RELATED#########

  def destroy
    #@post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


# allow attributes that I trust, ignore any scary malicious unsanctioned evil data
private
def post_params
  params.require(:post).permit(:title, :body, :is_required, :is_published, :is_featured)
  end

end

#strong parameters - changed recently

#POST requests are made when you click submit, the data ends up in the params hash. You have to whitelist 
#ANY requests end up in the params hash!

def find_post
 @post = Post.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1> Editing comments for <%= @post.title %></h1>-

<%= simple_form_for @comment, url: post_comment_path do |f| %>

<%= f.input :body %>

<%= f.button :submit %>

<% end%>

app/views/comments/new.html.erb
<h1>Comments for <%= @post.title %></h1>


<%= simple_form_for @comment, url: post_comments_path do |f| %>
<%= f.input :body %>
<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geopost</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<%= link_to "Home", root_path %>
		<%= link_to "Post something", new_post_path %>
		<%= link_to "Recent", root_path %>
		<%= link_to "Featured", root_path(featured: true) %>
	</header>

	<% flash.each do |key, value| %>
	<div class=""><% key %>
		<p><%= value %></p>
	</div>

	<% end %>

	<p>Params for this page are: <%= params %></p>
	

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb



<%= simple_form_for @post do |form| %>

<%=form.input :title %>
<%=form.input :body %>
<%=form.input :is_published %>
<%=form.input :is_featured %>

<%=form.button :submit %>

<!-- :submit is what it will do, "Create Post" is what I want it to say -->

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<section class="posts">
	<% @posts.each do |post| %>
		<div class="post">
			<h1><%= link_to post.title, post_path(post) %></h1>
			<p><%= truncate post.body, length: 20 %></p>
			<p>Posted <%= time_ago_in_words post.created_at %> ago.</p>
			
			</div>
	<% end %>
</section>

<!-- the (post) within post_path(post) comes from the block above i.e. do |post|

app/views/posts/new.html.erb
<h1>New post</h1>



<%= render "form" %>

<!-- form just comes from the name of the partial that we created before--!>
<!-- when rendering, needs to be a string when rendering within the view, but seems to need to be a symbol in the controller. Could use a symbol if you run the method .to_s to force it through if really needed to --!>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= simple_format @post.body %>
<!--<%= simple_format @post.comments %> -->

<p>Posted <%= time_ago_in_words @post.created_at %> ago</p>

<div class="actions">
	<%= link_to "Edit", edit_post_path(@post) %>
	<%= link_to "Delete", post_path(@post), method: :delete %>
	<%= link_to "Post comment", new_post_comment_path(@post) %>
</div>

<div class="comment">
	<% @comments.each do |comment| %>
		<%= comment.body %>
		<%= comment.created_at %>
		<%= link_to "Edit", edit_post_comment_path(@post, comment) %>
	<% end %>
</div>
 
 <!-- #post has an @ symbol as it was created in the controller. comment doesn't need one as it was the comment used in the block (e.g. do |comment|) -->



